version: '3'

services:

  ## Nginx Container ###########
  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - php-fpm

  ## PHP Container ###########
  php-fpm:
    build:
      context: .
      dockerfile: ./php-fpm/Dockerfile
    volumes:
      - ./src:/var/www
