version: '3'

services:

  ## Nginx Container ###########
  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "8080:80"
    environment:
      - SERVER_NAME=project.app
      - FASTCGI_BACKEND=php-fpm:9000
    volumes:
      - ./src/public:/var/www/public
    depends_on:
      - php-fpm

  ## PHP Container ###########
  php-fpm:
    build:
      context: .
      dockerfile: ./php-fpm/Dockerfile
      args:
        - INSTALL_MONGODB=false
        - INSTALL_OPCACHE=false
        - INSTALL_REDIS=false
    volumes:
      - ./src:/var/www
