version: '3'

services:

  ## Nginx Container ###########
  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "8080:80"
    environment:
      - SERVER_NAME=project.app
      - FASTCGI_BACKEND=php-fpm:9000
    volumes:
      - ./src/public:/var/www/public
    depends_on:
      - php-fpm

  ## PHP Container ###########
  php-fpm:
    build:
      context: .
      dockerfile: ./php-fpm/Dockerfile
      args:
        - INSTALL_GD=false
        - INSTALL_MONGODB=false
        - INSTALL_OPCACHE=false
        - INSTALL_REDIS=false
        - INSTALL_XDEBUG=false
    environment:
      - XDEBUG_CONFIG=idekey=PHPSTORM
      - PHP_IDE_CONFIG=serverName=localhost
    extra_hosts:
      # `echo $(ipconfig getifaddr en0)` for OSx
      # TODO: Linux should be 127.0.0.1 .. make sure it is
      - xdebug_host:0.0.0.0
    volumes:
      - ./src:/var/www
