version: '3'

services:

  ## Nginx Container ###########
  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "8080:80"
    environment:
      - SERVER_NAME=project.app
      - FASTCGI_BACKEND=php-fpm:9000
    volumes:
      - ./src/public:/var/www/public
    depends_on:
      - php-fpm

  ## PHP Container ###########
  php-fpm:
    build:
      context: .
      dockerfile: ./php-fpm/Dockerfile
      args:
        - INSTALL_APCU=false
        - INSTALL_GD=false
        - INSTALL_MEMCACHED=false
        - INSTALL_MONGODB=false
        - INSTALL_OPCACHE=false
        - INSTALL_PGSQL=false
        - INSTALL_REDIS=false
        - INSTALL_XDEBUG=false
    environment:
      - XDEBUG_CONFIG=idekey=PHPSTORM
      - PHP_IDE_CONFIG=serverName=localhost
    extra_hosts:
      # `echo $(ipconfig getifaddr en0)` for OSx
      # TODO: Linux should be 127.0.0.1 .. make sure it is
      - xdebug_host:0.0.0.0
    volumes:
      - ./src:/var/www
    depends_on:
      - mariadb
      - redis

  ## Queue Worker Container ###########
  queue-worker:
    build:
      context: .
      dockerfile: ./php-fpm/Dockerfile
    command:
      - "./artisan"
      - "queue:work"
    volumes:
      - ./src:/var/www
    depends_on:
      - mariadb
      - redis

  ## Database Container ###########
  mariadb:
    image: yobasystems/alpine-mariadb
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: docker
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root

  ## Redis Container ###########
  redis:
    image: redis:4.0-alpine
    command:
      - "redis-server"
      - "--appendonly"
      - "yes"
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  mariadb-data:
  redis-data:
